### ISSUE TITLE
Will not show over Modal

### ISSUE THREAD

**Issue by accessdeniedIT** [lucasferreira/react-native-flash-message#134]
Is there a way to show over a modal?

**Comment by lucasferreira** [comment]
Hi @accessdeniedIT 

Basicaly not, because native modals works on other thread above the main UI (where the default flash message works).

There were others past issues where you can find some workarounds:

https://github.com/lucasferreira/react-native-flash-message/issues?q=is%3Aissue+modal

By the way I suggest to work with local FlashMessage Instance inside de modal component.
