### ISSUE TITLE
Duration does not work on Android Samsung Galaxy S9 

### ISSUE THREAD

**Issue by CRiva** [lucasferreira/react-native-flash-message#15]
When I run the showMessage command with either default or specified duration, on the S9 the message flashes and then disappears immediately, it does not stay on screen as expected.

**Comment by lucasferreira** [comment]
Hi @CRiva,

As we can see here https://github.com/lucasferreira/react-native-flash-message/blob/master/src/FlashMessage.js#L427 the "hideout" it's a simple `setTimeout` using the "duration" prop.

I do not have access to a Galaxy S9 to test it more, so cold you help me to investigate this? Can you try some `setTimeout` random code to see if it works OK?

**Comment by CRiva** [comment]
I have used `setTimeout` in other places in my app, if that's what you meant by "random code." 
Those timeouts work as expected.

**Comment by rjriel** [comment]
I was having a serious issue getting the autoHide to work too. @CRiva were you seeing this issue in an emulator? That's where I was having problems and after doing debugging and research I came across this issue: https://github.com/facebook/react-native/issues/9030 which turns out is an annoying difference between the emulators time and your system time. I noticed my emulator was showing `12:41` for its time and my system was showing `12:42`. If I let the message sit there it eventually disappeared, so I think that's what was causing it.

Hope this is helpful

**Comment by lucasferreira** [comment]
Hi @rjriel thanks for this info.

Thats interesting a lot.

I don't know if it is the case of @CRiva since it reports that other `setTimeout` uses in his app are working well.

**Comment by lucasferreira** [comment]
Hi @CRiva another user report in this issue (https://github.com/lucasferreira/react-native-flash-message/issues/35#issuecomment-480185159) that his setTimeout problem it's about diference between clocks.

Did you remind if you are face some of this cases?

**Comment by CRiva** [comment]
We don't use many timeouts in our app. We use eventListeners to handle most situations involving time. 

I just tested out a simple `setTimeout` and that works on the S9

**Comment by KeeganFargher** [comment]
I recently experienced the same issue and I remembered having an issue with onPress / onLongPress while debug is active. [See here](https://github.com/facebook/react-native/issues/4944).

I disabled debugging and it stopped auto hiding.
