### ISSUE TITLE
Flash Message blocks UI thread

### ISSUE THREAD

**Issue by stephanoparaskeva** [lucasferreira/react-native-flash-message#151]
I display a flash message in development on each redux action dispatch as middleware, I display the message in the centre of the screen. It's really useful!

The only problem is, once a message displays I cannot do any actions or tap any buttons until it dissappears. I could reduce the duration but then I wont be able to see the message.

Any help?

**Comment by lucasferreira** [comment]
Hi @stephanoparaskeva 

The 'center' position it's the only one that's really block the entire UI, because we use some overlay View with 100%/100% above all the application.

The other positions for flash message are OK, just center that have this "issue".

And I will look forward to find some solution for this...

**Comment by edreyyo** [comment]
Any word on a fix, @lucasferreira? 🙂 I'm experiencing the same issue with the flash/toast at the bottom. Users aren't able to tap the bottom tabbar (see screenshot) until the flash/toast disappears. Thanks

<img width="472" alt="Screenshot_2021-12-20_at_16_36_16" src="https://user-images.githubusercontent.com/6125211/146794426-879a6ddf-e4b4-4f85-a80d-b193699dacfc.png">
